"""empty message

Revision ID: 855c83b2a9b2
Revises: b06bf75bf397
Create Date: 2022-03-19 23:11:42.088494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855c83b2a9b2'
down_revision = 'b06bf75bf397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'monthly')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('monthly', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
