"""empty message

Revision ID: b06bf75bf397
Revises: 
Create Date: 2022-03-19 22:55:11.691677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06bf75bf397'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('daily', sa.Boolean(), nullable=True))
    op.add_column('file', sa.Column('weekly', sa.Boolean(), nullable=True))
    op.add_column('file', sa.Column('monthly', sa.Boolean(), nullable=True))
    op.add_column('file', sa.Column('yearly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'yearly')
    op.drop_column('file', 'monthly')
    op.drop_column('file', 'weekly')
    op.drop_column('file', 'daily')
    # ### end Alembic commands ###
